language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
  - secure: CivEz5KutFHeb1DpKmINoL7FgPlrmYQkJWvc6GFX7fumLww6L6IiqpEghODb6cHHy37ar6n21m99w1xMy/1opm0xjhha4f3JP7CK3c5c6EaiiDz8YGZk1SLNQKlm5ROz+Q2fVzm5AscR+lWWnZ9mF7VVXIjLq2Yw3bfDd+Z0yiE=
  - secure: YP3qMEqlrC9YotD9D6AkWYUp8PST40I/iaNZkwkRXJcvbfXO3GdRZzEugthb5TqPTVW2MRNj2okqelCJMFfuMEqFzF1s8xf5aJ5kAMwpPUzDzF+AmV4QMR7y49PwSBmNqpIHTgx845RKJ2bB5pCFI0jHy/pTSHJ3BImKwE6bD8g=
